cc_library(
  name = 'jemalloc',
  export_incs = [
    'include'
  ],
  srcs = [
    'src/arena.c',
    'src/atomic.c',
    'src/base.c',
    'src/bitmap.c',
    'src/chunk.c',
    'src/chunk_dss.c',
    'src/chunk_mmap.c',
    'src/ckh.c',
    'src/ctl.c',
    'src/extent.c',
    'src/hash.c',
    'src/huge.c',
    'src/jemalloc.c',
    'src/mb.c',
    'src/mutex.c',
    'src/nstime.c',
    'src/pages.c',
    'src/prng.c',
    'src/prof.c',
    'src/quarantine.c',
    'src/rtree.c',
    'src/stats.c',
    'src/tcache.c',
    'src/ticker.c',
    'src/tsd.c',
    'src/util.c',
  ],
  deps = [
    '#rt',
  ],
  warning = 'no',
)
